CREATE TABLE session (
  id varchar(24) NOT NULL,
  tgt_id varchar(172) DEFAULT NULL,
  expiration timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  state BIGINT NOT NULL DEFAULT 0,
  requestor_id varchar(255) NOT NULL,
  url clob,
  forced_authenticate boolean NOT NULL,
  sessionuser LONG VARCHAR FOR BIT DATA,
  attributes LONG VARCHAR FOR BIT DATA,
  forced_userid clob,
  locale blob,
  selected_authn_profile blob,
  authn_profiles blob,
  passive boolean DEFAULT false,
  PRIMARY KEY (id)
);
-- sessionuser, attributes from clob/blob to varbinary

CREATE TABLE tgt (
  id varchar(172) NOT NULL,
  expiration timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tgtuser LONG VARCHAR FOR BIT DATA,
  authn_profile LONG VARCHAR FOR BIT DATA,
  authn_profile_ids LONG VARCHAR FOR BIT DATA,
  requestor_ids LONG VARCHAR FOR BIT DATA,
  attributes LONG VARCHAR FOR BIT DATA,
  PRIMARY KEY (id)
);

CREATE TABLE alias_store_sp (
  tgt_id varchar(172) NOT NULL,
  sp_id varchar(255) NOT NULL,
  aselect_credentials varchar(350) DEFAULT NULL,
  session_index varchar(343) DEFAULT NULL,
  transient_user_id varchar(256) DEFAULT NULL,
  persistent_user_id varchar(255) DEFAULT NULL,
  unspecified11_user_id varchar(255) DEFAULT NULL,
  unspecified20_user_id varchar(255) DEFAULT NULL,
  email_user_id varchar(255) DEFAULT NULL,
  PRIMARY KEY (tgt_id,sp_id)
);

CREATE TABLE alias_store_idp (
  tgt_id varchar(172) NOT NULL,
  idp_id varchar(255) NOT NULL,
  aselect_credentials varchar(512) DEFAULT NULL,
  session_index varchar(343) DEFAULT NULL,
  transient_user_id varchar(256) DEFAULT NULL,
  persistent_user_id varchar(255) DEFAULT NULL,
  unspecified11_user_id varchar(255) DEFAULT NULL,
  unspecified20_user_id varchar(255) DEFAULT NULL,
  email_user_id varchar(255) DEFAULT NULL,
  PRIMARY KEY (tgt_id,idp_id)
);

CREATE TABLE requestorpool_authnprofile (
  authn_profile_id varchar(48) NOT NULL,
  pool_id varchar(48) NOT NULL,
  order_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY (authn_profile_id,pool_id)
);

CREATE TABLE requestorpool_pool (
  id varchar(48) NOT NULL,
  friendlyname varchar(255) NOT NULL,
  enabled boolean DEFAULT true,
  preauthz_profile_id varchar(48) DEFAULT NULL,
  postauthz_profile_id varchar(48) DEFAULT NULL,
  forced boolean DEFAULT false,
  releasepolicy varchar(48) DEFAULT NULL,
  date_last_modified timestamp DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE requestorpool_properties (
  pool_id varchar(48) NOT NULL,
  name varchar(255) NOT NULL,
  value varchar(255) NOT NULL,
  PRIMARY KEY (pool_id,name)
);

CREATE TABLE requestorpool_requestor (
  id varchar(255) NOT NULL,
  pool_id varchar(48) NOT NULL,
  friendlyname varchar(255) NOT NULL,
  enabled boolean DEFAULT true,
  date_last_modified timestamp DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE requestorpool_requestor_properties (
  requestor_id varchar(255) NOT NULL,
  name varchar(255) NOT NULL,
  value varchar(255) NOT NULL,
  PRIMARY KEY (requestor_id,name)
);

CREATE TABLE authn_profile (
  id varchar(48) NOT NULL,
  friendlyname varchar(255) NOT NULL,
  enabled boolean DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE authn_profile_properties ( 
	profile_id varchar(48) NOT NULL,
	name varchar(255) NOT NULL,
	value varchar(255) NOT NULL,
	PRIMARY KEY(profile_id,name)
);

CREATE TABLE authn_method ( 
	id varchar(48) NOT NULL,
	profile_id varchar(48) NOT NULL,
  	order_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY UNIQUE,
	PRIMARY KEY(id,profile_id)  
);


CREATE TABLE attributerelease_policy (
  id varchar(48) NOT NULL,
  friendlyname varchar(255) DEFAULT NULL,
  enabled boolean DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE attributerelease_expression (
  policy_id varchar(48) NOT NULL,
  expression varchar(255) NOT NULL,
  PRIMARY KEY (policy_id,expression)
);

CREATE TABLE authz_profile (
  id varchar(48) NOT NULL,
  friendlyname varchar(255) DEFAULT NULL,
  enabled boolean DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE authz_method (
  id varchar(48) NOT NULL,
  profile_id varchar(48) NOT NULL,
  order_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY (id,profile_id)
);

CREATE TABLE ssoquery_whitelist (
  item varchar(255) NOT NULL,
  PRIMARY KEY (item)
);

CREATE TABLE users (
  userid VARCHAR(64) NOT NULL,
  password VARCHAR(64) NOT NULL,
  PRIMARY KEY (userid)
);

CREATE TABLE artifact(
  id VARCHAR(60) NOT NULL,
  issuer VARCHAR(255) DEFAULT NULL,
  relyingparty VARCHAR(255) DEFAULT NULL,
  expiration TIMESTAMP NOT NULL,
  message clob,
  PRIMARY KEY (id)
);


-- for saml2 authmethod:
CREATE TABLE saml2_orgs
(
  id VARCHAR(255) NOT NULL,
  sourceid blob NOT NULL,
  friendlyname VARCHAR(255) NOT NULL,
  metadata_url VARCHAR(255),
  metadata_timeout integer NOT NULL DEFAULT -1,
  metadata_file VARCHAR(255),
  enabled boolean DEFAULT true,
  acs_index boolean NOT NULL DEFAULT true,
  scoping boolean NOT NULL DEFAULT true,
  nameidpolicy boolean NOT NULL DEFAULT true,
  allow_create boolean,
  nameidformat VARCHAR(255) DEFAULT NULL,
  date_last_modified TIMESTAMP,
  avoid_subjconf boolean NOT NULL DEFAULT false,
  disable_sso boolean NOT NULL DEFAULT false,
  PRIMARY KEY (id)
);